### ISSUE TITLE
LWC / Aura Support

### ISSUE THREAD

**Issue by jonathanwiesel** [Oblongmana/vscode-salesforce-doc-lookup#7]
I'm really loving this extension, I hope people keep adopting it since I find it extremely useful.

I noticed that LWC / Aura support is not explicitly mentioned in the roadmap, is it being considered? 

I understand that implementation may change since that documentation doesn't follow the same structure as other doc types already supported but being technical documentation reference from the Salesforce Platform widely used I'm sure most will find it valuable.

**Comment by Oblongmana** [comment]
Great question - bit of a blind spot for me because I've not been working in Aura/LWC much lately. Will investigate today and see if I can ship something.

**Comment by Oblongmana** [comment]
I did quite a lot of digging today - while the majority of existing doc is an Angular app driven by toc json files, the Aura/LWC looks to be a "dogfood" type app, built on Aura, which has made extracting useful info quite challenging!

I've made some pretty extensive notes while digging into the component-library at [feature/lwc-aura-doc/notes/aura_lwc_component_docs.md](/Oblongmana/vscode-salesforce-doc-lookup/blob/feature/lwc-aura-doc/notes/aura_lwc_component_docs.md) - extremely rough notes as I tried to work things out. I think I've got an approach that should work however. 

Some mild CORS concerns, where I think VSCode isn't necessarily behaving as a standard browser would, so I'm likely going to have to tag this work as Experimental and leave it like that, to hedge my bets against any future changes to the way VSCode runs `fetch` requests.

Also added some notes about dealing with the Developer Guide tab as well [feature/lwc-aura-doc/notes/lwc_developer_guide.md](/Oblongmana/vscode-salesforce-doc-lookup/blob/feature/lwc-aura-doc/notes/lwc_developer_guide.md).

No guarantee on timeline for implementing, but this looks doable at minimum 👍

**Comment by Oblongmana** [comment]
@jonathanwiesel I couldn't leave this one unfinished - just pushed out another release (1.3.0) implementing this, and enabling searching of the breadcrumb that appears under each entry (https://marketplace.visualstudio.com/items/Oblongmana.vscode-salesforce-doc-lookup/changelog)

Marking this issue as Done. Do let me know by opening another Issue if you hit any bugs with this though - it's a pretty quick implementation, and I don't have any insight into how stable these Aura-based docs are over time. Hopefully not too unstable!

If you are finding the extension useful by the way, the extension page at https://marketplace.visualstudio.com/items?itemName=Oblongmana.vscode-salesforce-doc-lookup doesn't have any reviews, so if you get a chance to add one, feel free 😛

**Comment by jonathanwiesel** [comment]
Will definitely give it a try and leave some love in the marketplace.

Outstanding work!
